<?php

use Illuminate\Database\Seeder;

class MasterTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
            [
                'id' => 1,
                'type' => 'category',
                'code' => 'meat',
                'value' => '肉類',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 2,
                'type' => 'category',
                'code' => 'seafood',
                'value' => '魚介類',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 3,
                'type' => 'category',
                'code' => 'vegitable',
                'value' => '野菜類',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 4,
                'type' => 'category',
                'code' => 'dairy-product',
                'value' => '卵&乳製品',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 5,
                'type' => 'category',
                'code' => 'bean',
                'value' => '大豆製品',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 6,
                'type' => 'category',
                'code' => 'seasoning',
                'value' => '調味料',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 7,
                'type' => 'material_meat',
                'code' => 'pork_3',
                'value' => '豚ロース＆豚もも＆豚ヒレ',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 8,
                'type' => 'material_meat',
                'code' => 'pork_ibs',
                'value' => '豚バラ',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 9,
                'type' => 'material_meat',
                'code' => 'beef_loin',
                'value' => '牛ロース',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 10,
                'type' => 'material_meat',
                'code' => 'beef_2',
                'value' => '牛バラ＆牛タン',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 11,
                'type' => 'material_meat',
                'code' => 'beet_tenderloin',
                'value' => '牛ヒレ',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 12,
                'type' => 'material_meat',
                'code' => 'ram_loin',
                'value' => 'ラムロース',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 13,
                'type' => 'material_meat',
                'code' => 'ram_round',
                'value' => 'ラムもも',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],

            [
                'id' => 14,
                'type' => 'material_meat',
                'code' => 'chicken_cartilage',
                'value' => '鶏ナンコツ',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 15,
                'type' => 'material_meat',
                'code' => 'chicken_3',
                'value' => '鶏ムネ＆鶏もも＆鶏ささみ',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 16,
                'type' => 'material_meat',
                'code' => 'becon',
                'value' => 'ベーコン',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 17,
                'type' => 'material_meat',
                'code' => 'uncured_ham',
                'value' => '生ハム',
                'sort_no' => 1,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 18,
                'type' => 'material_seafood',
                'code' => 'clam',
                'value' => 'あさり',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 19,
                'type' => 'material_seafood',
                'code' => 'seafood_1',
                'value' => '秋刀魚＆鰹＆鮭＆ほっけ＆鮪（赤身）',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
             [
                'id' => 20,
                'type' => 'material_seafood',
                'code' => 'seafood_2',
                'value' => 'ししゃも＆しらす干し',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
             [
                'id' => 21,
                'type' => 'material_seafood',
                'code' => 'sesfood_3',
                'value' => '鰻＆鯖',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
             [
                'id' => 22,
                'type' => 'material_seafood',
                'code' => 'sardine',
                'value' => '鰯',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 23,
                'type' => 'material_seafood',
                'code' => 'seafood_4',
                'value' => 'イカ＆タコ',
                'sort_no' => 2,
                'deleted_at' => null,
                'deleted' => false,
            ],
             [
                'id' => 24,
                'type' => 'vegitable',
                'code' => 'soybean_sprout',
                'value' => '大豆もやし',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 25,
                'type' => 'vegitable',
                'code' => 'vegitable_1',
                'value' => 'ブロッコリー＆ちんげん菜',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 26,
                'type' => 'material_vegitable',
                'code' => 'avocado',
                'value' => 'アボカド',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 27,
                'type' => 'material_vegitable',
                'code' => 'spinach',
                'value' => 'ほうれん草',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 28,
                'type' => 'material_vegitable',
                'code' => 'vegitable_2',
                'value' => 'セロリ&レタス',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 29,
                'type' => 'material_vegitable',
                'code' => 'vegitable_3',
                'value' => '白菜＆きゅうり',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 30,
                'type' => 'material_vegitable',
                'code' => 'shiitake',
                'value' => 'しいたけ',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 31,
                'type' => 'material_vegitable',
                'code' => 'shimeji',
                'value' => 'しめじ',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 32,
                'type' => 'material_vegitable',
                'code' => 'maitake',
                'value' => '舞茸',
                'sort_no' => 3,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 33,
                'type' => 'material_dairy_product',
                'code' => 'egg',
                'value' => '卵',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 34,
                'type' => 'material_dairy_product',
                'code' => 'camembert cheese',
                'value' => 'カマンベールチーズ',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ], 
            [
                'id' => 35,
                'type' => 'material_dairy_product',
                'code' => 'cheeses',
                'value' => 'ゴーダチーズ＆チェダーチーズ',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 36,
                'type' => 'material_dairy_product',
                'code' => 'fresh_cream',
                'value' => '植物性生クリーム',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 37,
                'type' => 'material_dairy_product',
                'code' => 'butter',
                'value' => 'バター',
                'sort_no' => 4,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 38,
                'type' => 'material_bean',
                'code' => 'aburaage',
                'value' => '油揚げ',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 39,
                'type' => 'material_bean',
                'code' => 'toufu',
                'value' => '木綿豆腐',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 40,
                'type' => 'material_bean',
                'code' => 'toufu2',
                'value' => '絹豆腐',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 41,
                'type' => 'material_bean',
                'code' => 'natto',
                'value' => '納豆',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 42,
                'type' => 'material_bean',
                'code' => 'atsuageganmo',
                'value' => '厚揚げ＆がんもどき',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 43,
                'type' => 'material_bean',
                'code' => 'okara',
                'value' => 'おから',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 44,
                'type' => 'material_bean',
                'code' => 'tounyu',
                'value' => '無調整豆乳',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 45,
                'type' => 'material_bean',
                'code' => 'kinako',
                'value' => 'きな粉',
                'sort_no' => 5,
                'deleted_at' => null,
                'deleted' => false,
            ],
             [
                'id' => 46,
                'type' => 'material_seasoning',
                'code' => 'seasoning_1',
                'value' => '塩＆鰹だし＆鶏ガラだし中華だし',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 47,
                'type' => 'material_seasoning',
                'code' => 'vineger',
                'value' => '穀物酢',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 48,
                'type' => 'material_seasoning',
                'code' => 'soup kelp',
                'value' => '昆布だし',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 49,
                'type' => 'material_seasoning',
                'code' => 'mayonnaise',
                'value' => 'マヨネーズ',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 50,
                'type' => 'material_seasoning',
                'code' => 'black_pepper',
                'value' => '黒こしょう',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 51,
                'type' => 'material_seasoning',
                'code' => 'white_peper',
                'value' => '白こしょう',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 52,
                'type' => 'material_seasoning',
                'code' => 'soysouce',
                'value' => '薄口醤油',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 53,
                'type' => 'material_seasoning',
                'code' => 'sake',
                'value' => '料理酒',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 54,
                'type' => 'material_seasoning',
                'code' => 'consomme',
                'value' => '固形コンソメ',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
            [
                'id' => 55,
                'type' => 'material_seasoning',
                'code' => 'oil',
                'value' => 'オリーブオイル＆ごま油＆ラー油＆サラダ油',
                'sort_no' => 6,
                'deleted_at' => null,
                'deleted' => false,
            ],
//もしidが15,24,32,46,55なら0g
//もしidが8,12,19,23なら0.1g
//もしidが7,10,13,20,37,42なら0.2g
//もしidが11,16,21,27,33なら0.3g
//もしidが14,18なら0.4g
//もしidが17なら0.5g
//もしidが22なら0.7g
//もしidが25なら0.8g
//もしidが26,34,48なら0.9g
//もしidが39なら1.2g
//もしidが31なら1.3g
//もしidが30,35,38なら1.4g
//もしidが28,40なら1.7g
//もしidが29なら1.9g
//もしidが43なら2.3g
//もしidが47なら2.4g
//もしidが36,44なら2.9g
//もしidが49なら4.5g
//もしidが41なら4.6g
//もしidが52なら10.1g
//もしidが45なら14.1g
//もしidが53なら16.6g
//もしidが54なら30.3g
//もしidが50なら66.6g
//もしidが51なら70.1g
//もしidが45なら14.1g


        ];
        DB::table('master')->insert($arr);
    }
}
